export const DrActionTypes={
    REQUESTED:'REQUESTED'
}

export const WoListActionTypes={
    SET_SEARCH:'SET_SEARCH',
    WO_LIST:'WO_LIST'
}

export const TodoListReduxActionTypes={
    SET_TODO_LIST_REQUEST:'SET_TODO_LIST_REQUEST',
    SET_TODO_LIST_RECEIVED:'SET_TODO_LIST_RECEIVED',
    DELETE_TODO_LIST_REQUEST:'DELETE_TODO_LIST_REQUEST',
    CHECKED_TODO_LIST_REQUEST:'CHECKED_TODO_LIST_REQUEST',
    EDIT_TODO_LIST_REQUEST:'EDIT_TODO_LIST_REQUEST',
    SUBMIT_EDIT_TODO_LIST_REQUEST:'SUBMIT_EDIT_TODO_LIST_REQUEST',
    ADD_NEW_TODO_MODAL_REQUEST:'ADD_NEW_TODO_MODAL_REQUEST',
    VALUE_NEW_TODO_INPUT_REQUEST:'VALUE_NEW_TODO_INPUT_REQUEST',
    SUBMIT_NEW_TODO_INPUT_REQUEST:'SUBMIT_NEW_TODO_INPUT_REQUEST'
}

export const BackgroundChange={
    SET_BACKGROUND_REQUEST:'SET_BACKGROUND_REQUEST',
    SET_HEADER_COLOR_REQUEST:'SET_HEADER_COLOR_REQUEST'
}

export const ListInPractice={
    SET_LIST_REQUEST:'SET_LIST_REQUEST',
}

export const EditForm={
    SET_EDIT_INPUT:"SET_EDIT_INPUT",
    SET_SAVE_INPUT:"SET_SAVE_INPUT",
    SET_HANDLE_SAVE_EDIT_INPUT:"SET_HANDLE_SAVE_EDIT_INPUT",
}

